function D = Dmtrx(in1)
%DMTRX
%    D = DMTRX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Apr-2020 14:20:01

p = in1(4,:);
q = in1(5,:);
r = in1(6,:);
u_r = in1(1,:);
v_r = in1(2,:);
w_r = in1(3,:);
t2 = abs(q);
t3 = abs(r);
t4 = abs(v_r);
t5 = abs(w_r);
D = reshape([abs(u_r).*(8.1e+1./5.0e+1),0.0,0.0,0.0,0.0,0.0,0.0,t4.*1.31e+3,0.0,0.0,0.0,t4.*(1.59e+2./5.0e+1),0.0,0.0,t5.*1.31e+3,0.0,t5.*(-1.59e+2./5.0e+1),0.0,0.0,0.0,0.0,abs(p).*(1.3e+1./1.0e+2),0.0,0.0,0.0,0.0,t2.*(7.9e+1./1.25e+2),0.0,t2.*1.88e+2,0.0,0.0,t3.*(-7.9e+1./1.25e+2),0.0,0.0,0.0,t3.*1.88e+2],[6,6]);
